### ISSUE TITLE
Extension not listed in "Add new" extensions for 5.40

### ISSUE THREAD

**Issue by insaner** [twomice/com.joineryhq.emaildouble#3]
Does that mean this extension will not work with 5.40+? I'm new to all things CiviCRM, so if I've done something wrong, please let me know.

**Comment by twomice** [comment]
Hi @insaner It should work fine with current versions of civicrm. 

The reason it's not listed under "Add new" is because it has not been reviewed by the CiviCRM community, which is a requirement for inclusion on the in-app "Add new" screen.

This means that you'll need to install it manually. You could start with the instructions in the "Manual installation of native extensions" note under "Installing a new extension" in the CiviCRM documentation here: https://docs.civicrm.org/sysadmin/en/latest/customize/extensions/#installing-a-new-extension

If you're totally new to civicrm, I expect you may run into some questions while following those steps. Please feel free to ask here and I'll be glad to advise.

**Comment by insaner** [comment]
Hi @twomice , thank you for the quick reply! I had to hunt around for the default extensions path, and was able to find it and install. 

Quick questions: 
-How difficult is it to get reviewed and added to the official list?
-Should I file a new Issue to request that the form not be able to be submitted unless the emails match? The extension is not currently doing that, which kind of defeats the purpose for me.
-It would be great to expand on the idea of the extension to not just have double checks for emails but other fields too (though my use-case only requires email checking).

Thanks again!

**Comment by twomice** [comment]
Hi @insaner 

> -How difficult is it to get reviewed and added to the official list?

Not so hard really, but there are various reasons why we have not requested it for this extension (mostly the reason is just that we are busy with more pressing client concerns).

-Should I file a new Issue to request that the form not be able to be submitted unless the emails match? The extension is not currently doing that, which kind of defeats the purpose for me.

The extension should be doing that, so if it is not, yes, please file an issue explaining exactly the steps we could take to reproduce the issue in a clean civicrm installation.

> -It would be great to expand on the idea of the extension to not just have double checks for emails but other fields too (though my use-case only requires email checking).

We're always open to feature requests, for which you could file an issue. No promises, of course, but feel free to submit your ideas.

**Comment by insaner** [comment]
Hi @twomice , as requested I opened issue #4 to track it. I did test it again and sure enough, it's not working for me as intended. Let me know how I can help to test any fixes.
